% Define paths to images
leftImagePaths = {'C:\Users\DELL\Desktop\TesterCamera\images\stereoLeft\imageL0.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoLeft\imageL1.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoLeft\imageL13.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoLeft\imageL17.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoLeft\imageL18.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoLeft\imageL20.png',...
    };
rightImagePaths = {'C:\Users\DELL\Desktop\TesterCamera\images\stereoRight\imageR0.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoRight\imageR1.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoRight\imageR13.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoRight\imageR17.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoRight\imageR18.png',...
    'C:\Users\DELL\Desktop\TesterCamera\images\stereoRight\imageR20.png',...
    };

% Detect calibration pattern in images
checkerboardDetector = vision.calibration.stereo.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(checkerboardDetector, leftImagePaths, rightImagePaths);

% Generate world coordinates for the planar pattern keypoints
squareSizeMillimeters = 2.540000e+01;  % square size in millimeters
worldPoints = generateWorldPoints(checkerboardDetector, 'SquareSize', squareSizeMillimeters);

% Read one of the images from the first stereo pair
leftImage = imread(leftImagePaths{1});
[mrows, ncols, ~] = size(leftImage);

% Calibrate the stereo camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% Visualize reprojection errors
reprojectionErrorsFigure = figure; showReprojectionErrors(stereoParams);

% Visualize pattern locations
patternLocationsFigure = figure; showExtrinsics(stereoParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, stereoParams);

% Rectify stereo images using calibration data
rightImage = imread(rightImagePaths{1});
[leftRectifiedImage, rightRectifiedImage, reprojectionMatrix] = rectifyStereoImages(leftImage, rightImage, stereoParams);




